-- Illustrative sample entries from src/data/expressions.json and patterns.json (sample = true).
begin;
insert into public.expressions (id,title,original_text,language,literal,implied,setting,lenses,source_language,interpreter,rendering,single_source,sensitive,sample,status) values ('EX-001','Asking a parent for the meaning of a form term','Portal pe “domicile” likha hai, papa se poochna padega.','Hindi–English (code-switched: “portal”, “domicile”)','The portal says “domicile”; I will have to ask Dad.','The term is not part of the participant’s vocabulary and they rely on a family member to interpret official language. This is a pause to get help, not a refusal to continue.','Scholarship portal, first login, college computer lab',array['N','P']::text[],'Hindi–English (code-switched)','independent-interpreter','gloss',false,false,true,'approved') on conflict (id) do nothing;
insert into public.expressions (id,title,original_text,language,literal,implied,setting,lenses,source_language,interpreter,rendering,single_source,sensitive,sample,status) values ('EX-002','A fee request reads as a possible scam','Arre, fees maangenge kya?','Hindi','Oh, will they ask for fees?','Alarm. A request for money inside an official flow pattern-matches a scam, and trust drops at once. Observed with a step back from the screen.','Scholarship portal, payment step',array['T']::text[],'Hindi','research-coordinator','verbatim',true,false,true,'approved') on conflict (id) do nothing;
insert into public.expressions (id,title,original_text,language,literal,implied,setting,lenses,source_language,interpreter,rendering,single_source,sensitive,sample,status) values ('EX-003','Repeated document requests as a burden, not a puzzle','Haye, ab phir se sab documents?','Hindi','Oh no, all the documents again?','Fatigue and exasperation at being asked for the same documents more than once. “Haye” signals burden, not confusion. Treating it as an error state would miss the emotional weight.','Scholarship portal, document upload step',array['N']::text[],'Hindi','independent-interpreter','paraphrase',false,false,true,'approved') on conflict (id) do nothing;
insert into public.expressions (id,title,original_text,language,literal,implied,setting,lenses,source_language,interpreter,rendering,single_source,sensitive,sample,status) values ('EX-004','Hesitation before the final submit','Submit karne se pehle ek baar aur dekh loon.','Hindi–English (code-switched: “submit”)','Let me look once more before I submit.','Submitting feels irreversible. The participant wants reassurance that a mistake can still be fixed after this step.','Scholarship portal, final review screen',array['N','T']::text[],'Hindi–English (code-switched)',null,'gloss',null,false,true,'approved') on conflict (id) do nothing;
insert into public.expressions (id,title,original_text,language,literal,implied,setting,lenses,source_language,interpreter,rendering,single_source,sensitive,sample,status) values ('EX-005','Being the family’s translator for institutions','Ghar mein kisi ko yeh sab nahi aata, isliye main hi sab karta hoon.','Hindi','No one at home understands all this, so I am the one who does everything.','Pride and burden together. The participant acts as the family’s interpreter for institutions. Touches family circumstances.','Interview, daily-life conversation',array['P']::text[],'Hindi','independent-interpreter','verbatim',false,true,true,'approved') on conflict (id) do nothing;
insert into public.patterns (id,title,type,context,pattern,audience,tested_status,lens_n,lens_n_note,lens_p,lens_p_note,lens_t,lens_t_note,sample,status) values ('DL-001','Explain “domicile” in plain words, with the local term','Wording','Scholarship portal, document upload step','Certificate that shows you live in this state (Domicile / Niwas praman patra)','India 2','Partially confirmed','pass','First-time applicants understood it without help.','fail','Read aloud by an operator, the Hindi term was dropped and the meaning was lost.','untested',null,true,'approved') on conflict (id) do nothing;
insert into public.pattern_citations (pattern_id,expression_id) values ('DL-001','EX-001') on conflict do nothing;
insert into public.patterns (id,title,type,context,pattern,audience,tested_status,lens_n,lens_n_note,lens_p,lens_p_note,lens_t,lens_t_note,sample,status) values ('DL-002','Say plainly that this step is free','Wording','Scholarship portal, any step that could be mistaken for a payment request','This step is free. No one from the office will ask you for money.','India 2','Not yet tested','untested',null,'untested',null,'untested',null,true,'approved') on conflict (id) do nothing;
insert into public.pattern_citations (pattern_id,expression_id) values ('DL-002','EX-002') on conflict do nothing;
insert into public.patterns (id,title,type,context,pattern,audience,tested_status,lens_n,lens_n_note,lens_p,lens_p_note,lens_t,lens_t_note,sample,status) values ('DL-003','Reassure that answers can still be changed','Wording','Final review screen before submit','You can still change your answers after this step, until the last date.','India 2','Not yet tested','untested',null,'untested',null,'untested',null,true,'approved') on conflict (id) do nothing;
insert into public.pattern_citations (pattern_id,expression_id) values ('DL-003','EX-004') on conflict do nothing;
insert into public.patterns (id,title,type,context,pattern,audience,tested_status,lens_n,lens_n_note,lens_p,lens_p_note,lens_t,lens_t_note,sample,status) values ('DL-004','Show every required document on the first screen','Interaction','Start of a multi-step application','One checklist of all required documents before the first upload, so nothing is asked for twice.','India 2','Confirmed','pass',null,'pass','Operator could read the list aloud and tick items with the applicant.','pass',null,true,'approved') on conflict (id) do nothing;
insert into public.pattern_citations (pattern_id,expression_id) values ('DL-004','EX-003') on conflict do nothing;
commit;
