import manifest from '../data/booklet-assets.json';

// Page images generated by scripts/extract-booklet-assets.py. Ids: booklet pages
// are printed page numbers ("1.06", "4.12"); card-kit pages are "S1".."S8", "B1".."B7".

export interface PageImage {
  /** Site path (wrap with url() at the call site). */
  src: string;
  width: number;
  height: number;
}

type Manifest = { booklet: Record<string, { width: number; height: number }>; cardKit: Record<string, { width: number; height: number }> };
const m = manifest as unknown as Manifest;

export function bookletImage(id: string): PageImage {
  const e = m.booklet[id];
  if (!e) throw new Error(`No booklet page image "${id}". Run scripts/extract-booklet-assets.py.`);
  return { src: `/booklet/${id}.webp`, width: e.width, height: e.height };
}

export function cardKitImage(id: string): PageImage {
  const e = m.cardKit[id];
  if (!e) throw new Error(`No card-kit page image "${id}". Run scripts/extract-booklet-assets.py.`);
  return { src: `/card-kit/${id}.webp`, width: e.width, height: e.height };
}
